services:
  - type: web
    name: japanese-translator
    env: python
    buildCommand: pip install fastapi uvicorn
    startCommand: uvicorn main_simple:app --host 0.0.0.0 --port $PORT
    plan: starter