services:
  - type: web
    name: japanese-translator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        value: 103.97.126.29
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: dsvxxzme_itss
      - key: DB_USER
        value: dsvxxzme_itss
      - key: DB_PASSWORD
        value: 12345678
      - key: CUDA_AVAILABLE
        value: false
    autoDeploy: false